/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sikuli.script.natives;

public class Blob {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Blob(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Blob obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VisionProxyJNI.delete_Blob(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Blob() {
    this(VisionProxyJNI.new_Blob__SWIG_0(), true);
  }

  public Blob(SWIGTYPE_p_cv__Rect rect) {
    this(VisionProxyJNI.new_Blob__SWIG_1(SWIGTYPE_p_cv__Rect.getCPtr(rect)), true);
  }

  public boolean isContainedBy(Blob b) {
    return VisionProxyJNI.Blob_isContainedBy(swigCPtr, this, Blob.getCPtr(b), b);
  }

  public void setArea(double value) {
    VisionProxyJNI.Blob_area_set(swigCPtr, this, value);
  }

  public double getArea() {
    return VisionProxyJNI.Blob_area_get(swigCPtr, this);
  }

  public void setMb(int value) {
    VisionProxyJNI.Blob_mb_set(swigCPtr, this, value);
  }

  public int getMb() {
    return VisionProxyJNI.Blob_mb_get(swigCPtr, this);
  }

  public void setMg(int value) {
    VisionProxyJNI.Blob_mg_set(swigCPtr, this, value);
  }

  public int getMg() {
    return VisionProxyJNI.Blob_mg_get(swigCPtr, this);
  }

  public void setMr(int value) {
    VisionProxyJNI.Blob_mr_set(swigCPtr, this, value);
  }

  public int getMr() {
    return VisionProxyJNI.Blob_mr_get(swigCPtr, this);
  }

  public void setScore(int value) {
    VisionProxyJNI.Blob_score_set(swigCPtr, this, value);
  }

  public int getScore() {
    return VisionProxyJNI.Blob_score_get(swigCPtr, this);
  }

}
