/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sikuli.script.natives;

public final class TARGET_TYPE {
  public final static int IMAGE = 0;
  public final static int TEXT = IMAGE + 1;
  public final static int BUTTON = TEXT + 1;
}

